# Generated by Django 4.2.3 on 2023-07-31 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time_send',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='chat',
            name='date_creat',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
