# Generated by Django 4.2.3 on 2023-07-31 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_time_send_alter_chat_date_creat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat_id',
            new_name='chat',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
